services:
  etlapp:
    image: etlapp
    build:
      context: .
      dockerfile: EtlApp/Dockerfile
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ilujhasdhas73679zhansdjASDalsdjhasjdn
      - MSSQL_PID=Express
    ports:
      - "1433:1433"